/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HomeLazyImport = createFileRoute('/_home')()
const HomeIndexLazyImport = createFileRoute('/_home/')()
const HomeDashboardLazyImport = createFileRoute('/_home/dashboard')()

// Create/Update Routes

const HomeLazyRoute = HomeLazyImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_home.lazy').then((d) => d.Route))

const HomeIndexLazyRoute = HomeIndexLazyImport.update({
  path: '/',
  getParentRoute: () => HomeLazyRoute,
} as any).lazy(() => import('./routes/_home.index.lazy').then((d) => d.Route))

const HomeDashboardLazyRoute = HomeDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => HomeLazyRoute,
} as any).lazy(() =>
  import('./routes/_home.dashboard.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/_home/dashboard': {
      preLoaderRoute: typeof HomeDashboardLazyImport
      parentRoute: typeof HomeLazyImport
    }
    '/_home/': {
      preLoaderRoute: typeof HomeIndexLazyImport
      parentRoute: typeof HomeLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  HomeLazyRoute.addChildren([HomeDashboardLazyRoute, HomeIndexLazyRoute]),
])

/* prettier-ignore-end */
