/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Essai2Import } from './routes/essai2'
import { Route as layoutImport } from './routes/__layout'
import { Route as R404Import } from './routes/__404'
import { Route as PostsPostIdEditImport } from './routes/posts_.$postId.edit'

// Create Virtual Routes

const EssaiLazyImport = createFileRoute('/essai')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const PostIdLazyImport = createFileRoute('/post/$id')()

// Create/Update Routes

const EssaiLazyRoute = EssaiLazyImport.update({
  path: '/essai',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/essai.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const Essai2Route = Essai2Import.update({
  path: '/essai2',
  getParentRoute: () => rootRoute,
} as any)

const layoutRoute = layoutImport.update({
  id: '/__layout',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/__404',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PostIdLazyRoute = PostIdLazyImport.update({
  path: '/post/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/post.$id.lazy').then((d) => d.Route))

const PostsPostIdEditRoute = PostsPostIdEditImport.update({
  path: '/posts/$postId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/__404': {
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/__layout': {
      preLoaderRoute: typeof layoutImport
      parentRoute: typeof rootRoute
    }
    '/essai2': {
      preLoaderRoute: typeof Essai2Import
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/essai': {
      preLoaderRoute: typeof EssaiLazyImport
      parentRoute: typeof rootRoute
    }
    '/post/$id': {
      preLoaderRoute: typeof PostIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId/edit': {
      preLoaderRoute: typeof PostsPostIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  R404Route,
  layoutRoute,
  Essai2Route,
  AboutLazyRoute,
  EssaiLazyRoute,
  PostIdLazyRoute,
  PostsPostIdEditRoute,
])

/* prettier-ignore-end */
